server:
  port: 80    #80表示注册到Consul服务器的服务消费者端口号


spring:
  application:
    name: consul-consumer-order    #服务别名----注册到Consul注册中心的名称
  ###consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}