server:
  port: 3344

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


spring:
  application:
    name: cloud-config-center #注册到Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChuiXue0105/springcloud-config.git    #Github上面的git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
        #默认读取分支
        default-label: main
#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
