server:
  port: 8006    #8006表示注册到Consul服务器的支付服务提供者端口号


spring:
  application:
    name: consul-provider-payment    #服务别名----注册到Consul注册中心的名称
###consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}