server:
  port: 80    #80表示注册到ZooKeeper服务器的支付服务提供者端口号


spring:
  application:
    name: cloud-consumer-order    #服务别名----注册到ZooKeeper注册中心的名称
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181